#!/usr/bin/env node
/**
 * One-shot: fills the "partner" (Get in touch) form + `footer.build.partner`
 * translations across every non-English locale catalog.
 *
 * Idempotent: only adds keys that don't already exist. Re-run safely.
 * After running, execute `node tools/sync-locales.mjs`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const LOC = join(ROOT, 'locales');

// Product / brand terms intentionally kept in Latin script across all locales:
// DigiByte, DigiAssets, GitHub, GitHub Discussions, JavaScript.
const T = {
	af: {
		eyebrow: "Kontak ons",
		title: "Wil jy met DigiByte werk?",
		lead: "Wisselplatform-notering, beursienintegrasies, DigiAssets-projekte, pers. Vertel ons waaraan jy werk en 'n DigiByte-gemeenskapslid sal by jou terugkom.",
		nameLabel: "Jou naam", emailLabel: "E-pos", orgLabel: "Organisasie", optional: "(opsioneel)",
		interestLabel: "Ek stel belang in", collab: "Samewerking",
		integration: "Integrasie (beurs / beursie / diens)", digiassets: "DigiAssets-projek",
		media: "Media / pers", other: "Ander", messageLabel: "Vertel ons 'n bietjie meer",
		consent: "Deur in te dien, stem jy in dat jou boodskap aan 'n DigiByte-gemeenskapslid via ons vormverwerker gestuur word. Sien die <a href=\"/privacy-app.html\">privaatheidskennisgewing</a> vir besonderhede.",
		submit: "Stuur boodskap",
		noscript: "Hierdie vorm benodig JavaScript. Kontak asseblief die DigiByte-gemeenskap deur die <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>-forum.",
		footerLink: "Werk saam &amp; integreer",
	},
	ar: {
		eyebrow: "تواصل معنا", title: "تريد العمل مع DigiByte؟",
		lead: "إدراج في المنصات، تكاملات المحافظ، مشاريع DigiAssets، الصحافة. أخبرنا بما تعمل عليه وسيتواصل معك أحد أعضاء مجتمع DigiByte.",
		nameLabel: "اسمك", emailLabel: "البريد الإلكتروني", orgLabel: "المؤسسة", optional: "(اختياري)",
		interestLabel: "أنا مهتم بـ", collab: "التعاون",
		integration: "التكامل (بورصة / محفظة / خدمة)", digiassets: "مشروع DigiAssets",
		media: "إعلام / صحافة", other: "أخرى", messageLabel: "أخبرنا بالمزيد",
		consent: "بإرسالك، فأنت توافق على إعادة توجيه رسالتك إلى أحد أعضاء مجتمع DigiByte عبر معالج النموذج الخاص بنا. اطلع على <a href=\"/privacy-app.html\">إشعار الخصوصية</a> للتفاصيل.",
		submit: "إرسال الرسالة",
		noscript: "يتطلب هذا النموذج JavaScript. يرجى التواصل مع مجتمع DigiByte عبر منتدى <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "تعاون وتكامل",
	},
	bg: {
		eyebrow: "Свържете се с нас", title: "Искате ли да работите с DigiByte?",
		lead: "Листване на борси, интеграции на портфейли, DigiAssets проекти, преса. Разкажете ни какво изграждате и член на общността на DigiByte ще се свърже с вас.",
		nameLabel: "Вашето име", emailLabel: "Имейл", orgLabel: "Организация", optional: "(по избор)",
		interestLabel: "Интересувам се от", collab: "Сътрудничество",
		integration: "Интеграция (борса / портфейл / услуга)", digiassets: "DigiAssets проект",
		media: "Медии / преса", other: "Друго", messageLabel: "Разкажете ни малко повече",
		consent: "С изпращането се съгласявате съобщението ви да бъде препратено към член на общността на DigiByte чрез нашия обработчик на формуляри. Вижте <a href=\"/privacy-app.html\">известието за поверителност</a> за подробности.",
		submit: "Изпрати съобщение",
		noscript: "Този формуляр изисква JavaScript. Моля, свържете се с общността на DigiByte чрез форума <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "Сътрудничи &amp; интегрирай",
	},
	cs: {
		eyebrow: "Ozvěte se nám", title: "Chcete spolupracovat s DigiByte?",
		lead: "Listing na burzách, integrace peněženek, projekty DigiAssets, tisk. Řekněte nám, na čem pracujete, a člen komunity DigiByte se vám ozve.",
		nameLabel: "Vaše jméno", emailLabel: "E-mail", orgLabel: "Organizace", optional: "(volitelné)",
		interestLabel: "Mám zájem o", collab: "Spolupráce",
		integration: "Integrace (burza / peněženka / služba)", digiassets: "Projekt DigiAssets",
		media: "Média / tisk", other: "Jiné", messageLabel: "Řekněte nám více",
		consent: "Odesláním souhlasíte s tím, že vaše zpráva bude prostřednictvím našeho zpracovatele formulářů předána členovi komunity DigiByte. Podrobnosti viz <a href=\"/privacy-app.html\">oznámení o ochraně soukromí</a>.",
		submit: "Odeslat zprávu",
		noscript: "Tento formulář vyžaduje JavaScript. Kontaktujte prosím komunitu DigiByte prostřednictvím fóra <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "Spolupracujte &amp; integrujte",
	},
	da: {
		eyebrow: "Kontakt os", title: "Vil du arbejde sammen med DigiByte?",
		lead: "Børsnoteringer, wallet-integrationer, DigiAssets-projekter, presse. Fortæl os, hvad du arbejder på, og et DigiByte-fællesskabsmedlem vender tilbage til dig.",
		nameLabel: "Dit navn", emailLabel: "E-mail", orgLabel: "Organisation", optional: "(valgfri)",
		interestLabel: "Jeg er interesseret i", collab: "Samarbejde",
		integration: "Integration (børs / wallet / tjeneste)", digiassets: "DigiAssets-projekt",
		media: "Medier / presse", other: "Andet", messageLabel: "Fortæl os lidt mere",
		consent: "Ved at indsende accepterer du, at din besked videresendes til et DigiByte-fællesskabsmedlem via vores formularbehandler. Se <a href=\"/privacy-app.html\">privatlivsmeddelelsen</a> for detaljer.",
		submit: "Send besked",
		noscript: "Denne formular kræver JavaScript. Kontakt venligst DigiByte-fællesskabet via <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>-forummet i stedet.",
		footerLink: "Samarbejd &amp; integrér",
	},
	de: {
		eyebrow: "Kontakt aufnehmen", title: "Möchtest du mit DigiByte arbeiten?",
		lead: "Börsen-Listings, Wallet-Integrationen, DigiAssets-Projekte, Presse. Erzähle uns, woran du arbeitest, und ein Mitglied der DigiByte-Community meldet sich bei dir.",
		nameLabel: "Dein Name", emailLabel: "E-Mail", orgLabel: "Organisation", optional: "(optional)",
		interestLabel: "Ich interessiere mich für", collab: "Zusammenarbeit",
		integration: "Integration (Börse / Wallet / Dienst)", digiassets: "DigiAssets-Projekt",
		media: "Medien / Presse", other: "Sonstiges", messageLabel: "Erzähle uns mehr",
		consent: "Mit dem Absenden erklärst du dich damit einverstanden, dass deine Nachricht über unseren Formulardienst an ein Mitglied der DigiByte-Community weitergeleitet wird. Details siehe <a href=\"/privacy-app.html\">Datenschutzhinweis</a>.",
		submit: "Nachricht senden",
		noscript: "Dieses Formular benötigt JavaScript. Bitte kontaktiere die DigiByte-Community stattdessen über das <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>-Forum.",
		footerLink: "Zusammenarbeit &amp; Integration",
	},
	el: {
		eyebrow: "Επικοινωνήστε μαζί μας", title: "Θέλετε να συνεργαστείτε με το DigiByte;",
		lead: "Καταχωρήσεις σε ανταλλακτήρια, ενσωματώσεις πορτοφολιών, έργα DigiAssets, τύπος. Πείτε μας τι φτιάχνετε και ένα μέλος της κοινότητας DigiByte θα επικοινωνήσει μαζί σας.",
		nameLabel: "Το όνομά σας", emailLabel: "Email", orgLabel: "Οργανισμός", optional: "(προαιρετικό)",
		interestLabel: "Με ενδιαφέρει", collab: "Συνεργασία",
		integration: "Ενσωμάτωση (ανταλλακτήριο / πορτοφόλι / υπηρεσία)", digiassets: "Έργο DigiAssets",
		media: "Μέσα / τύπος", other: "Άλλο", messageLabel: "Πείτε μας λίγα ακόμη",
		consent: "Με την υποβολή συμφωνείτε ότι το μήνυμά σας θα προωθηθεί σε μέλος της κοινότητας DigiByte μέσω του επεξεργαστή φορμών μας. Δείτε την <a href=\"/privacy-app.html\">ειδοποίηση απορρήτου</a> για λεπτομέρειες.",
		submit: "Αποστολή μηνύματος",
		noscript: "Αυτή η φόρμα απαιτεί JavaScript. Επικοινωνήστε με την κοινότητα DigiByte μέσω του φόρουμ <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "Συνεργασία &amp; ενσωμάτωση",
	},
	es: {
		eyebrow: "Contacta con nosotros", title: "¿Quieres colaborar con DigiByte?",
		lead: "Listados en exchanges, integraciones de wallets, proyectos DigiAssets, prensa. Cuéntanos en qué estás trabajando y un miembro de la comunidad DigiByte te responderá.",
		nameLabel: "Tu nombre", emailLabel: "Correo electrónico", orgLabel: "Organización", optional: "(opcional)",
		interestLabel: "Me interesa", collab: "Colaboración",
		integration: "Integración (exchange / wallet / servicio)", digiassets: "Proyecto DigiAssets",
		media: "Medios / prensa", other: "Otro", messageLabel: "Cuéntanos un poco más",
		consent: "Al enviar, aceptas que tu mensaje sea reenviado a un miembro de la comunidad DigiByte a través de nuestro procesador de formularios. Consulta el <a href=\"/privacy-app.html\">aviso de privacidad</a> para más detalles.",
		submit: "Enviar mensaje",
		noscript: "Este formulario requiere JavaScript. Ponte en contacto con la comunidad DigiByte a través del foro <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "Colabora e integra",
	},
	fa: {
		eyebrow: "با ما در تماس باشید", title: "می‌خواهید با DigiByte همکاری کنید؟",
		lead: "درج در صرافی‌ها، یکپارچه‌سازی کیف پول‌ها، پروژه‌های DigiAssets، رسانه. به ما بگویید روی چه چیزی کار می‌کنید و یکی از اعضای جامعه DigiByte با شما تماس خواهد گرفت.",
		nameLabel: "نام شما", emailLabel: "ایمیل", orgLabel: "سازمان", optional: "(اختیاری)",
		interestLabel: "من علاقه‌مند به", collab: "همکاری",
		integration: "یکپارچه‌سازی (صرافی / کیف پول / سرویس)", digiassets: "پروژه DigiAssets",
		media: "رسانه / مطبوعات", other: "سایر", messageLabel: "کمی بیشتر برای ما بگویید",
		consent: "با ارسال، شما موافقت می‌کنید که پیام شما از طریق پردازشگر فرم ما به یکی از اعضای جامعه DigiByte ارسال شود. جزئیات در <a href=\"/privacy-app.html\">اعلامیه حریم خصوصی</a>.",
		submit: "ارسال پیام",
		noscript: "این فرم به JavaScript نیاز دارد. لطفاً از طریق انجمن <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a> با جامعه DigiByte در تماس باشید.",
		footerLink: "همکاری و یکپارچه‌سازی",
	},
	fi: {
		eyebrow: "Ota yhteyttä", title: "Haluatko työskennellä DigiByten kanssa?",
		lead: "Pörssilistaukset, lompakkointegraatiot, DigiAssets-projektit, media. Kerro mitä rakennat, niin DigiByte-yhteisön jäsen ottaa sinuun yhteyttä.",
		nameLabel: "Nimesi", emailLabel: "Sähköposti", orgLabel: "Organisaatio", optional: "(valinnainen)",
		interestLabel: "Olen kiinnostunut", collab: "Yhteistyö",
		integration: "Integraatio (pörssi / lompakko / palvelu)", digiassets: "DigiAssets-projekti",
		media: "Media / lehdistö", other: "Muu", messageLabel: "Kerro lisää",
		consent: "Lähettämällä hyväksyt, että viestisi välitetään DigiByte-yhteisön jäsenelle lomakekäsittelijämme kautta. Katso lisätiedot <a href=\"/privacy-app.html\">tietosuojailmoituksesta</a>.",
		submit: "Lähetä viesti",
		noscript: "Tämä lomake vaatii JavaScriptin. Ota yhteyttä DigiByte-yhteisöön <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a> -foorumin kautta.",
		footerLink: "Yhteistyö &amp; integraatio",
	},
	fil: {
		eyebrow: "Makipag-ugnayan", title: "Gusto mo bang makipagtulungan sa DigiByte?",
		lead: "Exchange listings, wallet integrations, DigiAssets projects, press. Sabihin sa amin kung ano ang ginagawa mo at may isang miyembro ng komunidad ng DigiByte na sasagot sa iyo.",
		nameLabel: "Iyong pangalan", emailLabel: "Email", orgLabel: "Organisasyon", optional: "(opsyonal)",
		interestLabel: "Interesado ako sa", collab: "Pakikipagtulungan",
		integration: "Integrasyon (exchange / wallet / serbisyo)", digiassets: "Proyektong DigiAssets",
		media: "Media / press", other: "Iba pa", messageLabel: "Sabihin sa amin ang higit pa",
		consent: "Sa pagsusumite, sumasang-ayon kang ipapadala ang iyong mensahe sa isang miyembro ng komunidad ng DigiByte sa pamamagitan ng aming form processor. Tingnan ang <a href=\"/privacy-app.html\">paunawa sa privacy</a> para sa mga detalye.",
		submit: "Ipadala ang mensahe",
		noscript: "Nangangailangan ng JavaScript ang form na ito. Mangyaring makipag-ugnayan sa komunidad ng DigiByte sa pamamagitan ng <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a> forum.",
		footerLink: "Makipagtulungan at mag-integrate",
	},
	fr: {
		eyebrow: "Contactez-nous", title: "Envie de travailler avec DigiByte ?",
		lead: "Listing sur exchanges, intégrations de wallets, projets DigiAssets, presse. Dites-nous sur quoi vous travaillez et un membre de la communauté DigiByte vous répondra.",
		nameLabel: "Votre nom", emailLabel: "E-mail", orgLabel: "Organisation", optional: "(facultatif)",
		interestLabel: "Je m'intéresse à", collab: "Collaboration",
		integration: "Intégration (exchange / wallet / service)", digiassets: "Projet DigiAssets",
		media: "Médias / presse", other: "Autre", messageLabel: "Dites-nous en plus",
		consent: "En envoyant, vous acceptez que votre message soit transmis à un membre de la communauté DigiByte via notre processeur de formulaires. Voir l'<a href=\"/privacy-app.html\">avis de confidentialité</a> pour plus de détails.",
		submit: "Envoyer le message",
		noscript: "Ce formulaire nécessite JavaScript. Merci de contacter la communauté DigiByte via le forum <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "Collaborer &amp; intégrer",
	},
	hi: {
		eyebrow: "संपर्क करें", title: "क्या आप DigiByte के साथ काम करना चाहते हैं?",
		lead: "एक्सचेंज लिस्टिंग, वॉलेट इंटीग्रेशन, DigiAssets प्रोजेक्ट, प्रेस। हमें बताएं कि आप क्या बना रहे हैं और DigiByte समुदाय का एक सदस्य आपसे संपर्क करेगा।",
		nameLabel: "आपका नाम", emailLabel: "ईमेल", orgLabel: "संगठन", optional: "(वैकल्पिक)",
		interestLabel: "मुझे रुचि है", collab: "सहयोग",
		integration: "एकीकरण (एक्सचेंज / वॉलेट / सेवा)", digiassets: "DigiAssets परियोजना",
		media: "मीडिया / प्रेस", other: "अन्य", messageLabel: "हमें और बताएं",
		consent: "सबमिट करके, आप सहमत हैं कि आपका संदेश हमारे फ़ॉर्म प्रोसेसर के माध्यम से DigiByte समुदाय के एक सदस्य को अग्रेषित किया जाएगा। विवरण के लिए <a href=\"/privacy-app.html\">गोपनीयता नोटिस</a> देखें।",
		submit: "संदेश भेजें",
		noscript: "इस फ़ॉर्म को JavaScript की आवश्यकता है। कृपया <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a> फ़ोरम के माध्यम से DigiByte समुदाय से संपर्क करें।",
		footerLink: "सहयोग करें और एकीकृत करें",
	},
	hr: {
		eyebrow: "Kontaktirajte nas", title: "Želite li surađivati s DigiByteom?",
		lead: "Listanja na burzama, integracije novčanika, DigiAssets projekti, mediji. Recite nam na čemu radite i član zajednice DigiByte će vam se javiti.",
		nameLabel: "Vaše ime", emailLabel: "E-pošta", orgLabel: "Organizacija", optional: "(neobavezno)",
		interestLabel: "Zanima me", collab: "Suradnja",
		integration: "Integracija (burza / novčanik / usluga)", digiassets: "DigiAssets projekt",
		media: "Mediji / tisak", other: "Ostalo", messageLabel: "Recite nam više",
		consent: "Slanjem prihvaćate da će vaša poruka biti proslijeđena članu zajednice DigiByte putem naše obrade obrazaca. Pogledajte <a href=\"/privacy-app.html\">obavijest o privatnosti</a> za detalje.",
		submit: "Pošalji poruku",
		noscript: "Ovaj obrazac zahtijeva JavaScript. Kontaktirajte zajednicu DigiByte putem foruma <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "Surađujte i integrirajte",
	},
	hu: {
		eyebrow: "Lépjen kapcsolatba", title: "Szeretne együttműködni a DigiByte-tal?",
		lead: "Tőzsdei listázások, tárca-integrációk, DigiAssets projektek, sajtó. Meséljen róla, mit épít, és a DigiByte közösség egy tagja hamarosan válaszol.",
		nameLabel: "Az Ön neve", emailLabel: "E-mail", orgLabel: "Szervezet", optional: "(nem kötelező)",
		interestLabel: "Érdeklődöm", collab: "Együttműködés",
		integration: "Integráció (tőzsde / tárca / szolgáltatás)", digiassets: "DigiAssets projekt",
		media: "Média / sajtó", other: "Egyéb", messageLabel: "Mondjon el többet",
		consent: "A beküldéssel elfogadja, hogy üzenetét űrlapfeldolgozónkon keresztül továbbítjuk a DigiByte közösség egy tagjának. Részletek az <a href=\"/privacy-app.html\">adatvédelmi tájékoztatóban</a>.",
		submit: "Üzenet küldése",
		noscript: "Ez az űrlap JavaScriptet igényel. Kérjük, vegye fel a kapcsolatot a DigiByte közösséggel a <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a> fórumon.",
		footerLink: "Együttműködés &amp; integráció",
	},
	id: {
		eyebrow: "Hubungi kami", title: "Ingin bekerja sama dengan DigiByte?",
		lead: "Pencantuman di bursa, integrasi dompet, proyek DigiAssets, pers. Ceritakan yang sedang Anda kerjakan dan anggota komunitas DigiByte akan menghubungi Anda.",
		nameLabel: "Nama Anda", emailLabel: "Email", orgLabel: "Organisasi", optional: "(opsional)",
		interestLabel: "Saya tertarik pada", collab: "Kolaborasi",
		integration: "Integrasi (bursa / dompet / layanan)", digiassets: "Proyek DigiAssets",
		media: "Media / pers", other: "Lainnya", messageLabel: "Ceritakan lebih banyak",
		consent: "Dengan mengirimkan, Anda setuju pesan Anda diteruskan ke anggota komunitas DigiByte melalui pemroses formulir kami. Lihat <a href=\"/privacy-app.html\">pemberitahuan privasi</a> untuk detail.",
		submit: "Kirim pesan",
		noscript: "Formulir ini memerlukan JavaScript. Silakan hubungi komunitas DigiByte melalui forum <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "Kolaborasi &amp; integrasi",
	},
	it: {
		eyebrow: "Contattaci", title: "Vuoi collaborare con DigiByte?",
		lead: "Listing su exchange, integrazioni di wallet, progetti DigiAssets, stampa. Raccontaci a cosa stai lavorando e un membro della community DigiByte ti risponderà.",
		nameLabel: "Il tuo nome", emailLabel: "Email", orgLabel: "Organizzazione", optional: "(opzionale)",
		interestLabel: "Mi interessa", collab: "Collaborazione",
		integration: "Integrazione (exchange / wallet / servizio)", digiassets: "Progetto DigiAssets",
		media: "Media / stampa", other: "Altro", messageLabel: "Dicci di più",
		consent: "Inviando accetti che il tuo messaggio venga inoltrato a un membro della community DigiByte tramite il nostro processore di form. Vedi l'<a href=\"/privacy-app.html\">informativa sulla privacy</a> per i dettagli.",
		submit: "Invia messaggio",
		noscript: "Questo modulo richiede JavaScript. Contatta la community DigiByte tramite il forum <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "Collabora &amp; integra",
	},
	ja: {
		eyebrow: "お問い合わせ", title: "DigiByteとの連携をご希望ですか？",
		lead: "取引所への上場、ウォレット連携、DigiAssetsプロジェクト、メディア。取り組んでいる内容をお聞かせいただければ、DigiByteコミュニティのメンバーからご返信します。",
		nameLabel: "お名前", emailLabel: "メールアドレス", orgLabel: "所属組織", optional: "（任意）",
		interestLabel: "興味のある分野", collab: "コラボレーション",
		integration: "連携（取引所／ウォレット／サービス）", digiassets: "DigiAssetsプロジェクト",
		media: "メディア／プレス", other: "その他", messageLabel: "もう少し詳しく",
		consent: "送信すると、当社のフォーム処理サービスを通じて、DigiByteコミュニティのメンバーへメッセージが転送されることに同意したものとみなされます。詳細は<a href=\"/privacy-app.html\">プライバシー通知</a>をご覧ください。",
		submit: "メッセージを送る",
		noscript: "このフォームはJavaScriptが必要です。<a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>フォーラムからDigiByteコミュニティにご連絡ください。",
		footerLink: "連携＆統合",
	},
	ms: {
		eyebrow: "Hubungi kami", title: "Mahu bekerjasama dengan DigiByte?",
		lead: "Penyenaraian di bursa, integrasi dompet, projek DigiAssets, media. Beritahu kami apa yang anda sedang bina dan ahli komuniti DigiByte akan menghubungi anda.",
		nameLabel: "Nama anda", emailLabel: "E-mel", orgLabel: "Organisasi", optional: "(pilihan)",
		interestLabel: "Saya berminat dengan", collab: "Kerjasama",
		integration: "Integrasi (bursa / dompet / perkhidmatan)", digiassets: "Projek DigiAssets",
		media: "Media / akhbar", other: "Lain-lain", messageLabel: "Ceritakan lebih lanjut",
		consent: "Dengan menghantar, anda bersetuju mesej anda akan dimajukan kepada ahli komuniti DigiByte melalui pemproses borang kami. Lihat <a href=\"/privacy-app.html\">notis privasi</a> untuk butiran.",
		submit: "Hantar mesej",
		noscript: "Borang ini memerlukan JavaScript. Sila hubungi komuniti DigiByte melalui forum <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "Bekerjasama &amp; integrasi",
	},
	nb: {
		eyebrow: "Ta kontakt", title: "Vil du samarbeide med DigiByte?",
		lead: "Børsnoteringer, wallet-integrasjoner, DigiAssets-prosjekter, presse. Fortell oss hva du jobber med, så tar et medlem av DigiByte-fellesskapet kontakt.",
		nameLabel: "Ditt navn", emailLabel: "E-post", orgLabel: "Organisasjon", optional: "(valgfri)",
		interestLabel: "Jeg er interessert i", collab: "Samarbeid",
		integration: "Integrasjon (børs / wallet / tjeneste)", digiassets: "DigiAssets-prosjekt",
		media: "Medier / presse", other: "Annet", messageLabel: "Fortell oss litt mer",
		consent: "Ved å sende inn samtykker du til at meldingen din videresendes til et medlem av DigiByte-fellesskapet via vår skjemabehandler. Se <a href=\"/privacy-app.html\">personvernerklæringen</a> for detaljer.",
		submit: "Send melding",
		noscript: "Dette skjemaet krever JavaScript. Ta kontakt med DigiByte-fellesskapet via <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>-forumet.",
		footerLink: "Samarbeid &amp; integrer",
	},
	nl: {
		eyebrow: "Neem contact op", title: "Wil je met DigiByte samenwerken?",
		lead: "Exchange-listings, wallet-integraties, DigiAssets-projecten, pers. Vertel ons waar je aan werkt en een lid van de DigiByte-community neemt contact met je op.",
		nameLabel: "Je naam", emailLabel: "E-mail", orgLabel: "Organisatie", optional: "(optioneel)",
		interestLabel: "Ik ben geïnteresseerd in", collab: "Samenwerking",
		integration: "Integratie (exchange / wallet / dienst)", digiassets: "DigiAssets-project",
		media: "Media / pers", other: "Anders", messageLabel: "Vertel ons wat meer",
		consent: "Door in te sturen ga je ermee akkoord dat je bericht via onze formulierverwerker aan een lid van de DigiByte-community wordt doorgestuurd. Zie de <a href=\"/privacy-app.html\">privacyverklaring</a> voor details.",
		submit: "Bericht versturen",
		noscript: "Dit formulier vereist JavaScript. Neem contact op met de DigiByte-community via het <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>-forum.",
		footerLink: "Samenwerken &amp; integreren",
	},
	pl: {
		eyebrow: "Skontaktuj się", title: "Chcesz współpracować z DigiByte?",
		lead: "Notowania na giełdach, integracje portfeli, projekty DigiAssets, prasa. Opowiedz nam, nad czym pracujesz, a członek społeczności DigiByte skontaktuje się z Tobą.",
		nameLabel: "Twoje imię", emailLabel: "E-mail", orgLabel: "Organizacja", optional: "(opcjonalnie)",
		interestLabel: "Interesuje mnie", collab: "Współpraca",
		integration: "Integracja (giełda / portfel / usługa)", digiassets: "Projekt DigiAssets",
		media: "Media / prasa", other: "Inne", messageLabel: "Opowiedz nam więcej",
		consent: "Wysyłając, zgadzasz się na przekazanie Twojej wiadomości członkowi społeczności DigiByte za pośrednictwem naszego procesora formularzy. Szczegóły w <a href=\"/privacy-app.html\">informacji o prywatności</a>.",
		submit: "Wyślij wiadomość",
		noscript: "Ten formularz wymaga JavaScript. Skontaktuj się ze społecznością DigiByte przez forum <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "Współpracuj &amp; integruj",
	},
	pt: {
		eyebrow: "Entre em contacto", title: "Quer trabalhar com a DigiByte?",
		lead: "Listagens em exchanges, integrações de carteiras, projetos DigiAssets, imprensa. Conte-nos no que está a trabalhar e um membro da comunidade DigiByte irá responder-lhe.",
		nameLabel: "O seu nome", emailLabel: "E-mail", orgLabel: "Organização", optional: "(opcional)",
		interestLabel: "Estou interessado em", collab: "Colaboração",
		integration: "Integração (exchange / carteira / serviço)", digiassets: "Projeto DigiAssets",
		media: "Media / imprensa", other: "Outro", messageLabel: "Conte-nos mais",
		consent: "Ao enviar, concorda que a sua mensagem seja encaminhada a um membro da comunidade DigiByte através do nosso processador de formulários. Consulte o <a href=\"/privacy-app.html\">aviso de privacidade</a> para mais detalhes.",
		submit: "Enviar mensagem",
		noscript: "Este formulário requer JavaScript. Contacte a comunidade DigiByte através do fórum <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "Colaborar &amp; integrar",
	},
	"pt-br": {
		eyebrow: "Entre em contato", title: "Quer trabalhar com a DigiByte?",
		lead: "Listagens em exchanges, integrações de carteiras, projetos DigiAssets, imprensa. Conte-nos no que você está trabalhando e um membro da comunidade DigiByte entrará em contato.",
		nameLabel: "Seu nome", emailLabel: "E-mail", orgLabel: "Organização", optional: "(opcional)",
		interestLabel: "Tenho interesse em", collab: "Colaboração",
		integration: "Integração (exchange / carteira / serviço)", digiassets: "Projeto DigiAssets",
		media: "Mídia / imprensa", other: "Outro", messageLabel: "Conte-nos mais",
		consent: "Ao enviar, você concorda que sua mensagem seja encaminhada a um membro da comunidade DigiByte por meio do nosso processador de formulários. Consulte o <a href=\"/privacy-app.html\">aviso de privacidade</a> para mais detalhes.",
		submit: "Enviar mensagem",
		noscript: "Este formulário requer JavaScript. Entre em contato com a comunidade DigiByte pelo fórum <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "Colaborar &amp; integrar",
	},
	ro: {
		eyebrow: "Contactează-ne", title: "Vrei să colaborezi cu DigiByte?",
		lead: "Listări pe burse, integrări de portofele, proiecte DigiAssets, presă. Spune-ne la ce lucrezi și un membru al comunității DigiByte te va contacta.",
		nameLabel: "Numele tău", emailLabel: "E-mail", orgLabel: "Organizație", optional: "(opțional)",
		interestLabel: "Sunt interesat de", collab: "Colaborare",
		integration: "Integrare (bursă / portofel / serviciu)", digiassets: "Proiect DigiAssets",
		media: "Media / presă", other: "Altele", messageLabel: "Spune-ne mai multe",
		consent: "Prin trimitere, ești de acord ca mesajul tău să fie redirecționat către un membru al comunității DigiByte prin procesorul nostru de formulare. Consultă <a href=\"/privacy-app.html\">nota de confidențialitate</a> pentru detalii.",
		submit: "Trimite mesajul",
		noscript: "Acest formular necesită JavaScript. Contactează comunitatea DigiByte prin forumul <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "Colaborează &amp; integrează",
	},
	ru: {
		eyebrow: "Связаться с нами", title: "Хотите работать с DigiByte?",
		lead: "Листинги на биржах, интеграции кошельков, проекты DigiAssets, пресса. Расскажите, над чем работаете, и участник сообщества DigiByte свяжется с вами.",
		nameLabel: "Ваше имя", emailLabel: "Электронная почта", orgLabel: "Организация", optional: "(необязательно)",
		interestLabel: "Меня интересует", collab: "Сотрудничество",
		integration: "Интеграция (биржа / кошелёк / сервис)", digiassets: "Проект DigiAssets",
		media: "СМИ / пресса", other: "Другое", messageLabel: "Расскажите подробнее",
		consent: "Отправляя форму, вы соглашаетесь на пересылку вашего сообщения участнику сообщества DigiByte через наш обработчик форм. Подробности см. в <a href=\"/privacy-app.html\">уведомлении о конфиденциальности</a>.",
		submit: "Отправить сообщение",
		noscript: "Эта форма требует JavaScript. Свяжитесь с сообществом DigiByte через форум <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "Сотрудничество и интеграция",
	},
	sl: {
		eyebrow: "Stopite v stik", title: "Želite sodelovati z DigiByte?",
		lead: "Uvrstitve na borzah, integracije denarnic, projekti DigiAssets, mediji. Povejte nam, na čem delate, in član skupnosti DigiByte vas bo kontaktiral.",
		nameLabel: "Vaše ime", emailLabel: "E-pošta", orgLabel: "Organizacija", optional: "(neobvezno)",
		interestLabel: "Zanima me", collab: "Sodelovanje",
		integration: "Integracija (borza / denarnica / storitev)", digiassets: "Projekt DigiAssets",
		media: "Mediji / tisk", other: "Drugo", messageLabel: "Povejte nam več",
		consent: "S pošiljanjem se strinjate, da bo vaše sporočilo posredovano članu skupnosti DigiByte prek našega obdelovalnika obrazcev. Podrobnosti v <a href=\"/privacy-app.html\">obvestilu o zasebnosti</a>.",
		submit: "Pošlji sporočilo",
		noscript: "Ta obrazec zahteva JavaScript. Prosimo, obrnite se na skupnost DigiByte prek foruma <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "Sodeluj &amp; integriraj",
	},
	sq: {
		eyebrow: "Na kontaktoni", title: "Doni të punoni me DigiByte?",
		lead: "Listime në bursat, integrime portofolash, projekte DigiAssets, shtypi. Na thoni për çfarë po punoni dhe një anëtar i komunitetit DigiByte do t'ju përgjigjet.",
		nameLabel: "Emri juaj", emailLabel: "Email", orgLabel: "Organizata", optional: "(opsionale)",
		interestLabel: "Jam i interesuar për", collab: "Bashkëpunim",
		integration: "Integrim (bursë / portofol / shërbim)", digiassets: "Projekt DigiAssets",
		media: "Media / shtyp", other: "Tjetër", messageLabel: "Na tregoni më shumë",
		consent: "Duke dërguar, ju pranoni që mesazhi juaj të përcillet te një anëtar i komunitetit DigiByte nëpërmjet përpunuesit tonë të formularëve. Shihni <a href=\"/privacy-app.html\">njoftimin e privatësisë</a> për detaje.",
		submit: "Dërgo mesazhin",
		noscript: "Ky formular kërkon JavaScript. Kontaktoni komunitetin DigiByte përmes forumit <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "Bashkëpuno &amp; integro",
	},
	sv: {
		eyebrow: "Kontakta oss", title: "Vill du samarbeta med DigiByte?",
		lead: "Börsnoteringar, plånboksintegrationer, DigiAssets-projekt, press. Berätta vad du arbetar med, så hör en medlem av DigiByte-communityn av sig.",
		nameLabel: "Ditt namn", emailLabel: "E-post", orgLabel: "Organisation", optional: "(valfritt)",
		interestLabel: "Jag är intresserad av", collab: "Samarbete",
		integration: "Integration (börs / plånbok / tjänst)", digiassets: "DigiAssets-projekt",
		media: "Media / press", other: "Annat", messageLabel: "Berätta mer",
		consent: "Genom att skicka godkänner du att ditt meddelande vidarebefordras till en medlem av DigiByte-communityn via vår formulärhanterare. Se <a href=\"/privacy-app.html\">integritetsmeddelandet</a> för detaljer.",
		submit: "Skicka meddelande",
		noscript: "Detta formulär kräver JavaScript. Kontakta DigiByte-communityn via <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>-forumet.",
		footerLink: "Samarbeta &amp; integrera",
	},
	sw: {
		eyebrow: "Wasiliana nasi", title: "Ungependa kufanya kazi na DigiByte?",
		lead: "Kuorodhesha kwenye soko la sarafu, kuunganisha mikoba, miradi ya DigiAssets, vyombo vya habari. Tuambie unachofanyia kazi na mwanajumuiya wa DigiByte atakujibu.",
		nameLabel: "Jina lako", emailLabel: "Barua pepe", orgLabel: "Shirika", optional: "(hiari)",
		interestLabel: "Ninavutiwa na", collab: "Ushirikiano",
		integration: "Uunganishaji (soko / mkoba / huduma)", digiassets: "Mradi wa DigiAssets",
		media: "Vyombo vya habari", other: "Nyingine", messageLabel: "Tuambie zaidi",
		consent: "Kwa kutuma, unakubali ujumbe wako uwasilishwe kwa mwanajumuiya wa DigiByte kupitia kichakataji chetu cha fomu. Angalia <a href=\"/privacy-app.html\">taarifa ya faragha</a> kwa maelezo.",
		submit: "Tuma ujumbe",
		noscript: "Fomu hii inahitaji JavaScript. Tafadhali wasiliana na jumuiya ya DigiByte kupitia jukwaa la <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "Shirikiana &amp; unganisha",
	},
	th: {
		eyebrow: "ติดต่อเรา", title: "ต้องการทำงานร่วมกับ DigiByte หรือไม่?",
		lead: "การลิสต์บนกระดานเทรด การเชื่อมต่อกระเป๋าเงิน โปรเจกต์ DigiAssets สื่อ บอกเราว่าคุณกำลังทำอะไรอยู่ แล้วสมาชิกชุมชน DigiByte จะติดต่อกลับ",
		nameLabel: "ชื่อของคุณ", emailLabel: "อีเมล", orgLabel: "องค์กร", optional: "(ไม่บังคับ)",
		interestLabel: "ฉันสนใจใน", collab: "ความร่วมมือ",
		integration: "การเชื่อมต่อ (กระดานเทรด / กระเป๋า / บริการ)", digiassets: "โปรเจกต์ DigiAssets",
		media: "สื่อ / สื่อมวลชน", other: "อื่นๆ", messageLabel: "บอกเราเพิ่มเติม",
		consent: "การส่งหมายความว่าคุณยินยอมให้ข้อความของคุณถูกส่งต่อไปยังสมาชิกชุมชน DigiByte ผ่านตัวประมวลผลแบบฟอร์มของเรา ดูรายละเอียดได้ที่<a href=\"/privacy-app.html\">ประกาศความเป็นส่วนตัว</a>",
		submit: "ส่งข้อความ",
		noscript: "แบบฟอร์มนี้ต้องใช้ JavaScript โปรดติดต่อชุมชน DigiByte ผ่านฟอรัม <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>",
		footerLink: "ร่วมมือ &amp; เชื่อมต่อ",
	},
	tr: {
		eyebrow: "Bize ulaşın", title: "DigiByte ile çalışmak ister misiniz?",
		lead: "Borsa listelemeleri, cüzdan entegrasyonları, DigiAssets projeleri, basın. Neyin üzerinde çalıştığınızı anlatın; DigiByte topluluğundan bir üye sizinle iletişime geçsin.",
		nameLabel: "Adınız", emailLabel: "E-posta", orgLabel: "Kurum", optional: "(isteğe bağlı)",
		interestLabel: "İlgilendiğim konu", collab: "İşbirliği",
		integration: "Entegrasyon (borsa / cüzdan / hizmet)", digiassets: "DigiAssets projesi",
		media: "Medya / basın", other: "Diğer", messageLabel: "Biraz daha anlatın",
		consent: "Göndererek, mesajınızın form işleyicimiz aracılığıyla bir DigiByte topluluk üyesine iletilmesini kabul edersiniz. Ayrıntılar için <a href=\"/privacy-app.html\">gizlilik bildirimini</a> inceleyin.",
		submit: "Mesaj gönder",
		noscript: "Bu form JavaScript gerektirir. Lütfen DigiByte topluluğuna <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a> forumu üzerinden ulaşın.",
		footerLink: "İşbirliği &amp; entegrasyon",
	},
	vi: {
		eyebrow: "Liên hệ với chúng tôi", title: "Muốn hợp tác với DigiByte?",
		lead: "Niêm yết trên sàn, tích hợp ví, dự án DigiAssets, báo chí. Cho chúng tôi biết bạn đang xây dựng gì và một thành viên cộng đồng DigiByte sẽ liên hệ lại.",
		nameLabel: "Họ và tên của bạn", emailLabel: "Email", orgLabel: "Tổ chức", optional: "(tùy chọn)",
		interestLabel: "Tôi quan tâm đến", collab: "Hợp tác",
		integration: "Tích hợp (sàn / ví / dịch vụ)", digiassets: "Dự án DigiAssets",
		media: "Truyền thông / báo chí", other: "Khác", messageLabel: "Cho chúng tôi biết thêm",
		consent: "Bằng cách gửi, bạn đồng ý rằng tin nhắn của bạn sẽ được chuyển đến một thành viên cộng đồng DigiByte thông qua bộ xử lý biểu mẫu của chúng tôi. Xem <a href=\"/privacy-app.html\">thông báo bảo mật</a> để biết chi tiết.",
		submit: "Gửi tin nhắn",
		noscript: "Biểu mẫu này cần JavaScript. Vui lòng liên hệ cộng đồng DigiByte qua diễn đàn <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a>.",
		footerLink: "Hợp tác &amp; tích hợp",
	},
	zh: {
		eyebrow: "联系我们", title: "想与 DigiByte 合作吗？",
		lead: "交易所上币、钱包集成、DigiAssets 项目、媒体。告诉我们您正在做什么，DigiByte 社区成员会与您联系。",
		nameLabel: "您的姓名", emailLabel: "电子邮箱", orgLabel: "所属机构", optional: "（可选）",
		interestLabel: "我感兴趣的方向", collab: "合作",
		integration: "集成（交易所 / 钱包 / 服务）", digiassets: "DigiAssets 项目",
		media: "媒体 / 新闻", other: "其他", messageLabel: "告诉我们更多",
		consent: "提交即表示您同意通过我们的表单处理服务将您的消息转发给 DigiByte 社区成员。详情请见<a href=\"/privacy-app.html\">隐私声明</a>。",
		submit: "发送消息",
		noscript: "此表单需要 JavaScript。请通过 <a href=\"https://github.com/orgs/DigiByte-Core/discussions\" target=\"_blank\" rel=\"noopener\">GitHub Discussions</a> 论坛联系 DigiByte 社区。",
		footerLink: "合作 &amp; 集成",
	},
};

function keyMap(t) {
	return {
		"partner.eyebrow": t.eyebrow,
		"partner.title": t.title,
		"partner.lead": t.lead,
		"partner.form.name.label": t.nameLabel,
		"partner.form.email.label": t.emailLabel,
		"partner.form.org.label": t.orgLabel,
		"partner.form.optional": t.optional,
		"partner.form.interest.label": t.interestLabel,
		"partner.form.interest.collab": t.collab,
		"partner.form.interest.integration": t.integration,
		"partner.form.interest.digiassets": t.digiassets,
		"partner.form.interest.media": t.media,
		"partner.form.interest.other": t.other,
		"partner.form.message.label": t.messageLabel,
		"partner.form.consent": t.consent,
		"partner.form.submit": t.submit,
		"partner.form.noscript": t.noscript,
		"footer.build.partner": t.footerLink,
	};
}

let touched = 0, added = 0;
for (const [locale, t] of Object.entries(T)) {
	const p = join(LOC, `${locale}.json`);
	const raw = readFileSync(p, 'utf8');
	const obj = JSON.parse(raw);
	const km = keyMap(t);
	let localAdded = 0;
	for (const [k, v] of Object.entries(km)) {
		if (!(k in obj)) { obj[k] = v; localAdded++; }
	}
	if (localAdded > 0) {
		writeFileSync(p, JSON.stringify(obj, null, 2) + '\n', 'utf8');
		console.log(`[update] ${locale}.json (+${localAdded} keys)`);
		touched++;
		added += localAdded;
	} else {
		console.log(`[ok]     ${locale}.json (no changes)`);
	}
}
console.log(`\nDone. ${touched} file(s) updated, ${added} key(s) added.`);
